### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by shahiran250890** [PinkTie/laravel-dashboard-tabler#1]
Hi there. im trying using your dashboard template but when im try to call ajax  from my js file it give error Uncaught ReferenceError: $ is not defined at ajax.js:1. How can i fix this issue?

**Comment by KevinFairbanks** [comment]
Most likely you are loading the jquery.slim version which does not contain the ajax functions.

Add the full jQuery via NPM and then Modify resources/assets/js/bootstrap.js 

Change line 12 from  window.$ = window.jQuery = require("jquery/dist/jquery.slim"); to window.$ = window.jQuery = require("jquery/dist/jquery");

**Comment by KevinFairbanks** [comment]
Release 1.0.1 has been made with these changes
